spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# Change it if 8082 is not available
socket.feed.port=8082

# File Upload Limits (15MB limit)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true